on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Next Lint
        run: pnpm run lint
